# Generated by Django 4.1.2 on 2022-11-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TENDIK', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DOSEN',
        ),
        migrations.DeleteModel(
            name='MAHASISWA',
        ),
    ]
